# Site settings
title: "KR_YTlaw80"
bye_message: ":)"
baseurl: "/blog/"
url: "https://ytlaw80.github.io"
disqus: KR_YTlaw80
disqus_ID: YTlaw80
analytics:
  provider               : "G-S26T2WF923" 
  google:
    tracking_id          : "G-S26T2WF923"

# Header settings
nick: "KR_YTlaw80"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "YTlaw80"
blog:
    server: "https://www.ytlaw80.com"
    nick: "KR_YTlaw80"
fingerprint_key: "also visit https://www.youtube.com/@KR_YTlaw80"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
